Js popup window
Enning94/Personal-portfolio pull request #9
Opened 2022-07-22 12:56 UTC by Enning94

### JS popup window for personal portfolio-Figma template 2: Mobile and Desktop version

In this milestone, my partner and i:

-Added a popup window to the website
-Updated the page to render HTML information with javascript.

2022-07-22 13:10 UTC, roshan-bajgain requested changes
Hi @Enning94, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- PR has a good title and summary. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 13:10 UTC, roshan-bajgain commented on project-card.js
> +];
- [ ] Your design is not similar to the Figma design kindly make it similar to the design.
- [ ] kindly fix the buttons as well.
### Your design
![figma](https://user-images.githubusercontent.com/81727988/180445145-0969f1e9-713c-4c14-8cf8-322444742867.png)

2022-07-22 13:10 UTC, roshan-bajgain commented on project-card.js
> +  },
- [ ] Your popup is working properly but it effect the design as the design has more spacing on right kindly fix it
### Your design
![his](https://user-images.githubusercontent.com/81727988/180445606-d141c8ad-1462-4a1e-af4e-4599d6e0ede1.png)

2022-07-22 16:10 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @Enning94, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 16:10 UTC, leonardodiasb commented on project-card.js
> +                    <button type='button' class='btn btn-danger model-button '><a href='${project[0].liveVersion}'>See Live </a><i class='fa fa-external-link' aria-hidden='true'></i></button>
- [ ] Kindly fix the sizing of your image when the screen size changes. In some screen sizes, your popup doesn't look like the Figma design and makes the popup taller than the screen height.
- [ ] Kindly fix the popup sizing in the mobile view. The popup is larger and taller than the mobile screen size and this is making a bad user experience due to the scroll bars. Please fix that.
Your design:
![image](https://user-images.githubusercontent.com/61919617/180479508-2d100705-ff92-42b3-b4d6-7713aa0f86ee.png)
![image](https://user-images.githubusercontent.com/61919617/180479678-255e5426-dafc-4394-bc6f-49e721b22fbb.png)
![image](https://user-images.githubusercontent.com/61919617/180480009-7c7d3b84-7908-4ea8-aaaa-fe60f4816641.png)

2022-07-23 00:26 UTC, cynthiainga approved these changes
## STATUS APPROVED :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

Hi @Enning94, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- [ ] No linters errors :heavy_check_mark: 
- [ ] Good commit history :heavy_check_mark: 
- [ ] Fllow Github flow :heavy_check_mark:  

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-23 00:34 UTC, merged